import { useState, useCallback } from 'react';
import { GoogleGenerativeAI } from '@google/generative-ai';

export default function useGeminiMetadata() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const generateMetadata = useCallback(async (pdfFile, apiKey) => {
    if (!apiKey) {
      throw new Error('API key is required. Set your Gemini API key in settings.');
    }
    
    setLoading(true);
    setError(null);

    try {
      // 1. Prepare file: Slice first 1.5MB of PDF to optimize API transport speed and token limits
      const maxSliceSize = 1.5 * 1024 * 1024;
      const slicedBlob = pdfFile.size > maxSliceSize ? pdfFile.slice(0, maxSliceSize) : pdfFile;
      
      const base64Data = await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.readAsDataURL(slicedBlob);
        reader.onload = () => {
          const base64String = reader.result.split(',')[1];
          resolve(base64String);
        };
        reader.onerror = error => reject(error);
      });

      // 2. Initialize Gemini API Client
      const genAI = new GoogleGenerativeAI(apiKey);
      const model = genAI.getGenerativeModel({ 
        model: 'gemini-2.5-flash',
        generationConfig: {
          responseMimeType: "application/json",
        }
      });

      // 3. Construct prompt instructing the model to output strict metadata JSON
      const prompt = `Analyze the beginning of this PDF book file and extract structured metadata details. 
      Generate appropriate values for the following fields based on the content:
      - title: The name of the book
      - author: The name of the author(s)
      - description: A concise 2-3 sentence overview of what the book is about
      - tags: An array of 3-5 keywords or tags representing the book themes/topics (e.g. ["Engineering", "JavaScript", "Algorithms"])
      - categories: An array of 1-2 broader genres (e.g. ["Technology", "Science", "Biography", "Fiction"])
      - publicationYear: The year the book was published (4-digit string, or null if unknown)
      
      Return ONLY a JSON object containing these keys. Do not include markdown code block syntax.`;

      const parts = [
        {
          inlineData: {
            data: base64Data,
            mimeType: 'application/pdf'
          }
        },
        { text: prompt }
      ];

      const result = await model.generateContent(parts);
      const responseText = await result.response.text();
      
      // Clean up backtick code blocks if generated by model despite configuration
      const cleanJsonText = responseText.replace(/```json|```/gi, '').trim();
      const metadata = JSON.parse(cleanJsonText);
      
      setLoading(false);
      return metadata;
    } catch (err) {
      console.error('Gemini Metadata Generation failed:', err);
      setError(err.message || 'Failed to extract metadata. Make sure the API key is correct and file is valid.');
      setLoading(false);
      throw err;
    }
  }, []);

  return {
    generateMetadata,
    loading,
    error
  };
}
